"""
Logic Unit Management Context
"""
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field
from .._01_path_decomposition.path_decomposition_context import Step


@dataclass
class LogicUnit:
    """
    Represents an aggregated Logic Unit — segments sharing the same cache_key
    across multiple paths, used as the unit for LLM reasoning.
    Compatible with LLMFrontend2's caching system.
    """
    cache_key: str              # Generated by extract_unique_function_chain
    segment_type: str           # 'backward', 'intermediate', 'forward'
    steps: List[Step]          # Original steps from path
    
    # Step relationships for call/return analysis
    steps_relationships: Dict[Any, str] = field(default_factory=dict)  # Maps step keys to relation types
    
    # Shared variables for config formatting (same for all paths using this unit)
    shared_variables: Dict[str, Any] = field(default_factory=dict)  # Config formatting vars
    
    # Variable being tracked (should be same for all paths using this unit)
    variable_name: str = ""     # The tainted variable name
    
    # Tracking
    paths_using: List[str] = field(default_factory=list)  # All paths using this unit
    is_cached: bool = False    # Whether result exists in cache
    cached_result: Optional[Dict] = None   # Cached analysis result
    analysis_result: Optional[Dict] = None # New analysis result

    # Per-function merged constraints from cross-variant analysis
    merged_constraints: Optional[Dict[str, Dict]] = None

    # Whether any function had propagation differences across variants
    has_propagation_variants: bool = False

    # Per-function variant details for differing functions only
    # Structure: { "funcB@path/to/file.c": { "variant_count": 2, "variants": [...] } }
    variant_details: Optional[Dict[str, Dict]] = None

    # Whether this unit was created from a virtual single-point step
    is_virtual: bool = False

    # Transient: holds conversation history until dumped by ReasoningDumpStorage
    conversation_history: Optional[List[Dict]] = field(default_factory=list)

    def add_path(self, path_id: str):
        """Add a path that uses this Logic Unit"""
        if path_id not in self.paths_using:
            self.paths_using.append(path_id)
    
    def extract_shared_variables(self):
        """Extract shared_variables from steps for config formatting"""
        if not self.steps:
            return
            
        # Based on segment type, extract appropriate shared variables
        if self.segment_type == 'backward':
            # Extract from the last step's toPoint (the source)
            last_step = self.steps[-1]
            self.shared_variables = {
                'outer_backward_behavior_variable': last_step.toPoint.variable,
                'outer_backward_behavior_function_name': last_step.toPoint.functionName,
                'outer_backward_behavior_line_code': last_step.toPoint.lineCode,
                'outer_backward_behavior_line_number': last_step.toPoint.line
            }
            self.variable_name = last_step.toPoint.variable
            
        elif self.segment_type == 'forward':
            # Extract from the first step's fromPoint (starting point)
            first_step = self.steps[0]
            # Forward analysis might need different shared variables
            self.shared_variables = {
                'sink_variable': self.steps[-1].toPoint.variable,
                'sink_function_name': self.steps[-1].toPoint.functionName,
                'sink_line_code': self.steps[-1].toPoint.lineCode,
                'sink_line_number': self.steps[-1].toPoint.line
            }
            self.variable_name = first_step.fromPoint.variable
            
        elif self.segment_type == 'intermediate':
            # Intermediate analysis variables
            if self.steps:
                self.variable_name = self.steps[0].fromPoint.variable
                # Intermediate might need minimal shared variables
                self.shared_variables = {
                    'variable_name': self.variable_name
                }
    
    def get_usage_count(self) -> int:
        """Get number of paths using this Logic Unit"""
        return len(self.paths_using)
    
    def get_result(self) -> Optional[Dict]:
        """Get available result (cached or analyzed)"""
        return self.cached_result or self.analysis_result


@dataclass
class LogicUnitRegistry:
    """Registry of all Logic Units"""
    units: Dict[str, LogicUnit] = field(default_factory=dict)
    units_by_type: Dict[str, List[str]] = field(default_factory=lambda: {
        'backward': [],
        'intermediate': [],
        'forward': []
    })
    units_by_variable: Dict[str, List[str]] = field(default_factory=dict)