"""
Logic Unit Manager - manages reusable analysis segments
"""
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field
import hashlib
from collections import defaultdict


@dataclass
class LogicUnit:
    """
    Represents an aggregated Logic Unit — segments sharing the same cache_key
    across multiple paths, used as the unit for LLM reasoning.
    Compatible with LLMFrontend2's caching system.
    """
    cache_key: str              # Generated by extract_unique_function_chain
    segment_type: str           # 'backward', 'intermediate', 'forward'
    steps: List[Any]           # Original steps from path
    variable_name: str         # Variable being analyzed
    paths_using: List[str] = field(default_factory=list)  # Paths using this unit
    is_cached: bool = False    # Whether result exists in cache
    cached_result: Optional[Dict] = None   # Cached analysis result
    analysis_result: Optional[Dict] = None # New analysis result
    
    def add_path(self, path_id: str):
        """Add a path that uses this Logic Unit"""
        if path_id not in self.paths_using:
            self.paths_using.append(path_id)
    
    def get_usage_count(self) -> int:
        """Get number of paths using this Logic Unit"""
        return len(self.paths_using)
    
    def get_first_step(self) -> Optional[Any]:
        """Get the first step for display purposes"""
        return self.steps[0] if self.steps else None
    
    def get_last_step(self) -> Optional[Any]:
        """Get the last step for display purposes"""
        return self.steps[-1] if self.steps else None
    
    def get_function_chain(self) -> str:
        """Get human-readable function chain"""
        if not self.steps:
            return ""
        
        functions = []
        for step in self.steps:
            if hasattr(step, 'node1') and hasattr(step.node1, 'function_name'):
                func = step.node1.function_name
                if not functions or functions[-1] != func:
                    functions.append(func)
        
        return " -> ".join(functions)


class LogicUnitManager:
    """
    Manages all Logic Units in the analysis
    """
    
    def __init__(self):
        self.units: Dict[str, LogicUnit] = {}  # cache_key -> LogicUnit
        self.units_by_type: Dict[str, List[str]] = defaultdict(list)
        self.units_by_variable: Dict[str, List[str]] = defaultdict(list)
    
    def register_unit(self, cache_key: str, segment_type: str, 
                     steps: List[Any], variable_name: str) -> LogicUnit:
        """
        Register a new Logic Unit or return existing one
        """
        if cache_key not in self.units:
            # Create new Logic Unit
            unit = LogicUnit(
                cache_key=cache_key,
                segment_type=segment_type,
                steps=steps,
                variable_name=variable_name
            )
            
            # Store in registry
            self.units[cache_key] = unit
            self.units_by_type[segment_type].append(cache_key)
            self.units_by_variable[variable_name].append(cache_key)
            
        return self.units[cache_key]
    
    def get_unit(self, cache_key: str) -> Optional[LogicUnit]:
        """Get a Logic Unit by its cache key"""
        return self.units.get(cache_key)
    
    def get_all_units(self) -> List[LogicUnit]:
        """Get all registered Logic Units"""
        return list(self.units.values())
    
    def get_units_by_type(self, segment_type: str) -> List[LogicUnit]:
        """Get all Logic Units of a specific type"""
        cache_keys = self.units_by_type.get(segment_type, [])
        return [self.units[key] for key in cache_keys]
    
    def get_units_by_variable(self, variable_name: str) -> List[LogicUnit]:
        """Get all Logic Units for a specific variable"""
        cache_keys = self.units_by_variable.get(variable_name, [])
        return [self.units[key] for key in cache_keys]
    
    def get_uncached_units(self) -> List[LogicUnit]:
        """Get all Logic Units that don't have cached results"""
        return [unit for unit in self.units.values() if not unit.is_cached]
    
    def get_uncached_units_by_priority(self) -> List[LogicUnit]:
        """
        Get uncached units sorted by usage frequency (descending)
        Units used by more paths get higher priority
        """
        uncached = self.get_uncached_units()
        return sorted(uncached, key=lambda u: u.get_usage_count(), reverse=True)
    
    def get_unit_count(self) -> int:
        """Get total number of unique Logic Units"""
        return len(self.units)
    
    def get_statistics(self) -> Dict[str, Any]:
        """Get comprehensive statistics about Logic Units"""
        total_units = len(self.units)
        if total_units == 0:
            return {
                'total_units': 0,
                'by_type': {},
                'cache_stats': {},
                'reuse_stats': {}
            }
        
        # Type distribution
        type_dist = {
            seg_type: len(units) 
            for seg_type, units in self.units_by_type.items()
        }
        
        # Cache statistics
        cached_count = sum(1 for unit in self.units.values() if unit.is_cached)
        cache_rate = cached_count / total_units
        
        # Reuse statistics
        usage_counts = [unit.get_usage_count() for unit in self.units.values()]
        max_usage = max(usage_counts) if usage_counts else 0
        avg_usage = sum(usage_counts) / len(usage_counts) if usage_counts else 0
        
        return {
            'total_units': total_units,
            'by_type': type_dist,
            'cache_stats': {
                'cached_units': cached_count,
                'uncached_units': total_units - cached_count,
                'cache_rate': cache_rate
            },
            'reuse_stats': {
                'max_path_count': max_usage,
                'avg_paths_per_unit': avg_usage,
                'single_use_units': sum(1 for c in usage_counts if c == 1),
                'multi_use_units': sum(1 for c in usage_counts if c > 1)
            }
        }
    
    def get_distribution_data(self) -> Dict[str, Any]:
        """Get data for distribution visualization"""
        distribution = defaultdict(int)
        
        for unit in self.units.values():
            usage_count = unit.get_usage_count()
            distribution[usage_count] += 1
        
        return {
            'usage_distribution': dict(distribution),
            'type_distribution': {
                seg_type: len(units) 
                for seg_type, units in self.units_by_type.items()
            },
            'variable_distribution': {
                var: len(units)
                for var, units in self.units_by_variable.items()
                if len(units) > 1  # Only show variables with multiple units
            }
        }
    
    def get_reuse_heatmap(self) -> List[Dict[str, Any]]:
        """
        Generate data for reuse heatmap visualization
        Returns list of units with their reuse information
        """
        heatmap_data = []
        
        for unit in self.units.values():
            if unit.get_usage_count() > 1:  # Only include reused units
                heatmap_data.append({
                    'cache_key': unit.cache_key,
                    'segment_type': unit.segment_type,
                    'variable_name': unit.variable_name,
                    'usage_count': unit.get_usage_count(),
                    'is_cached': unit.is_cached,
                    'function_chain': unit.get_function_chain()
                })
        
        # Sort by usage count for better visualization
        heatmap_data.sort(key=lambda x: x['usage_count'], reverse=True)
        
        return heatmap_data