#!/usr/bin/env python3
"""
Scanner Builder - Generate CWE scanner modules from YAML configuration

Directory Structure:
    StaticAnalysisBackend/
    ├── scanner_configs/           # YAML configuration files
    │   ├── 416-UseAfterFree.yaml
    │   ├── 843.yaml
    │   └── ...
    ├── builds/                    # Generated scanner modules
    │   ├── CWE-416-UseAfterFree/
    │   │   ├── codeql.py
    │   │   ├── query.ql
    │   │   ├── codeql/
    │   │   └── __init__.py
    │   └── CWE-843/
    │       ├── codeql.py
    │       └── __init__.py
    └── Utils/
        └── scanner_builder.py

Usage:
    # Build a single scanner
    python3 scanner_builder.py build 416-UseAfterFree

    # Build all scanners
    python3 scanner_builder.py build-all

    # Verify a build (runs test)
    python3 scanner_builder.py verify 416-UseAfterFree --test-db /path/to/codeql/db

    # List all available configs
    python3 scanner_builder.py list
"""

import os
import sys
import yaml
import shutil
import subprocess
from pathlib import Path
from typing import Dict, Any, Optional, List, Tuple


# Template for generated codeql.py files (local query mode)
CODEQL_LOCAL_TEMPLATE = '''"""
CWE-{cwe_code}: {cwe_name} Analysis

Auto-generated by scanner_builder.py
Uses local query.ql and codeql/ library.
"""

import sqlite3
import subprocess
import os
import shutil
import json
import sys

# Add StaticAnalysisBackend to path for Utils imports
_current_dir = os.path.dirname(os.path.abspath(__file__))
_static_backend_dir = os.path.dirname(os.path.dirname(_current_dir))
if _static_backend_dir not in sys.path:
    sys.path.insert(0, _static_backend_dir)

from Utils.SarifParser.process_metadata import Extractor

cwe_code = '{cwe_code}'
query_file_path = os.path.join(os.path.dirname(__file__), 'query.ql')
ql_search_path = os.path.join(os.path.dirname(__file__), 'codeql')
compression_level = {compression_level}


class CodeQLAnalysisHelper:
    def __init__(self, db_path='codeql_analysis.db', codeql_db_path=None):
        self.db_path = db_path
        self.conn = sqlite3.connect(db_path)
        self.cursor = self.conn.cursor()
        self.initialize_database()
        self.cwe_code = cwe_code
        self.query_file_path = query_file_path
        self.codeql_db_path = codeql_db_path

    def initialize_database(self):
        self.cursor.execute(\'\'\'
        CREATE TABLE IF NOT EXISTS analysis_result_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            project_name TEXT,
            cwe_code TEXT,
            item_index INTEGER,
            item_data TEXT,
            UNIQUE(project_name, cwe_code, item_index)
        )
        \'\'\')

        self.cursor.execute(\'\'\'
        CREATE TABLE IF NOT EXISTS analysis_summary (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            project_name TEXT,
            cwe_code TEXT,
            total_items INTEGER,
            UNIQUE(project_name, cwe_code)
        )
        \'\'\')
        self.conn.commit()

    def get_analysis_results(self, analysis_path, project_name, function_csv, source_path):
        self.cursor.execute(\'\'\'
        SELECT COUNT(*) FROM analysis_result_items
        WHERE project_name = ? AND cwe_code = ?
        \'\'\', (project_name, self.cwe_code))

        count = self.cursor.fetchone()[0]
        if count > 0:
            print("[+] Found analysis results in database.")
            self.cursor.execute(\'\'\'
            SELECT item_data FROM analysis_result_items
            WHERE project_name = ? AND cwe_code = ?
            ORDER BY item_index
            \'\'\', (project_name, self.cwe_code))

            infos_list = []
            for row in self.cursor.fetchall():
                item_data = json.loads(row[0])
                infos_list.append(item_data)
            return infos_list
        else:
            print("[+] Analysis results not found in database. Running CodeQL analysis...")
            infos_list = self.run_codeql_analysis(analysis_path, project_name, function_csv, source_path)
            return infos_list

    def run_codeql_analysis(self, analysis_path, project_name, function_csv, source_path):
        cache_dir = os.path.join(os.path.dirname(analysis_path.rstrip('%')), 'cache')
        os.makedirs(cache_dir, exist_ok=True)
        sarif_output_path = os.path.join(cache_dir, f'{{project_name}}-results.sarif')

        if not self.codeql_db_path:
            raise ValueError("CodeQL database path is not provided.")

        codeql_path = os.environ.get('CODEQL_PATH', 'codeql')
        if os.path.isdir(codeql_path):
            codeql_path = os.path.join(codeql_path, 'codeql')

        analyze_cmd = [
            codeql_path, 'database', 'analyze', self.codeql_db_path,
            query_file_path,
            '--format=sarifv2.1.0',
            '--output', sarif_output_path,
            '--search-path', ql_search_path,
            '--threads', '{cpu_threads}',
            '--rerun'
        ]

        subprocess.run(analyze_cmd, check=True)

        extractor = Extractor(sarif_output_path, function_csv, source_path)
        processed_info_list = extractor.extract_info(compression_level=compression_level)

        self.cursor.execute(\'\'\'
        DELETE FROM analysis_result_items
        WHERE project_name = ? AND cwe_code = ?
        \'\'\', (project_name, self.cwe_code))

        self.cursor.execute(\'\'\'
        DELETE FROM analysis_summary
        WHERE project_name = ? AND cwe_code = ?
        \'\'\', (project_name, self.cwe_code))

        for index, item in enumerate(processed_info_list):
            item_json = json.dumps(item, ensure_ascii=False)
            self.cursor.execute(\'\'\'
            INSERT INTO analysis_result_items (project_name, cwe_code, item_index, item_data)
            VALUES (?, ?, ?, ?)
            \'\'\', (project_name, self.cwe_code, index, item_json))

        self.cursor.execute(\'\'\'
        INSERT INTO analysis_summary (project_name, cwe_code, total_items)
        VALUES (?, ?, ?)
        \'\'\', (project_name, self.cwe_code, len(processed_info_list)))

        self.conn.commit()

        # Cleanup SARIF file only (preserve function CSV)
        if os.path.exists(sarif_output_path):
            os.remove(sarif_output_path)

        print(f"[+] Number of results: {{len(processed_info_list)}}")
        print(f"[+] Analysis complete. Results saved to database.")
        return processed_info_list

    def close(self):
        self.conn.close()
'''


class ScannerBuilder:
    """Builder for creating CWE scanner modules from YAML configuration."""

    def __init__(self, base_dir: str = None, configs_dir: str = None):
        """
        Initialize the scanner builder.

        Args:
            base_dir: Base directory (StaticAnalysisBackend)
            configs_dir: Optional external directory containing scanner YAMLs
        """
        if base_dir is None:
            base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        self.base_dir = base_dir
        self.configs_dir = (
            os.path.abspath(configs_dir)
            if configs_dir else os.path.join(base_dir, 'scanner_configs')
        )
        self.builds_dir = os.path.join(base_dir, 'builds')

    def list_configs(self) -> List[str]:
        """
        List all available YAML config files.

        Returns:
            List of config names (without .yaml extension)
        """
        configs = []
        if not os.path.exists(self.configs_dir):
            return configs

        for filename in os.listdir(self.configs_dir):
            if filename.endswith('.yaml'):
                configs.append(filename[:-5])  # Remove .yaml
        return sorted(configs)

    def load_config(self, name: str) -> Dict[str, Any]:
        """
        Load a YAML configuration file.

        Args:
            name: Config name (e.g., "416-UseAfterFree")

        Returns:
            Configuration dictionary
        """
        config_path = os.path.join(self.configs_dir, f'{name}.yaml')
        if not os.path.exists(config_path):
            raise FileNotFoundError(f"Config not found: {config_path}")

        with open(config_path, 'r') as f:
            config = yaml.safe_load(f)
        query = config.get('query', {})
        for key in ('ql_source_path', 'codeql_lib_source', 'fallback_lib'):
            value = query.get(key)
            if value and not os.path.isabs(value):
                query[key] = os.path.normpath(os.path.join(self.base_dir, value))
        query['ql_dependencies'] = {
            name: path if os.path.isabs(path) else os.path.normpath(os.path.join(self.base_dir, path))
            for name, path in query.get('ql_dependencies', {}).items()
        }
        return config

    def validate_config(self, config: Dict[str, Any], name: str) -> List[str]:
        """
        Validate a configuration.

        Returns:
            List of validation errors (empty if valid)
        """
        errors = []

        # Check required metadata
        if 'metadata' not in config:
            errors.append("Missing 'metadata' section")
        else:
            if 'cwe_code' not in config['metadata']:
                errors.append("Missing 'metadata.cwe_code'")
            if 'cwe_name' not in config['metadata']:
                errors.append("Missing 'metadata.cwe_name'")

        # Check query section
        if 'query' not in config:
            errors.append("Missing 'query' section")
        else:
            query = config['query']
            source = query.get('source', 'shared')

            if source == 'local':
                ql_source = query.get('ql_source_path')
                if not ql_source:
                    errors.append("Local query requires 'query.ql_source_path'")
                elif not os.path.exists(ql_source):
                    errors.append(f"Query file not found: {ql_source}")

                for module_path, dependency in query.get('ql_dependencies', {}).items():
                    if os.path.isabs(module_path) or '..' in Path(module_path).parts:
                        errors.append(f"QL dependency destination must stay inside the query pack: {module_path}")
                    if not os.path.isfile(dependency):
                        errors.append(f"QL dependency not found: {dependency}")

                codeql_lib = query.get('codeql_lib_source')
                fallback_lib = query.get('fallback_lib')

                if not codeql_lib and not fallback_lib:
                    errors.append("Local query requires 'query.codeql_lib_source' or 'query.fallback_lib'")
                elif codeql_lib and not os.path.exists(codeql_lib):
                    if not fallback_lib or not os.path.exists(fallback_lib):
                        errors.append(f"CodeQL library not found: {codeql_lib}")

            elif source == 'shared':
                if 'shared_path' not in query:
                    errors.append("Shared query requires 'query.shared_path'")

        return errors

    def get_codeql_lib_source(self, config: Dict[str, Any]) -> Optional[str]:
        """Get the CodeQL library source path from config."""
        query = config.get('query', {})

        primary = query.get('codeql_lib_source')
        if primary and os.path.exists(primary):
            return primary

        fallback = query.get('fallback_lib')
        if fallback and os.path.exists(fallback):
            return fallback

        return None

    def build(self, name: str, force: bool = False) -> bool:
        """
        Build a scanner module from config.

        Args:
            name: Config name (e.g., "416-UseAfterFree")
            force: Force rebuild even if files exist

        Returns:
            True if build succeeded
        """
        print(f"\nBuilding {name}...")

        # Load and validate config
        try:
            config = self.load_config(name)
        except Exception as e:
            print(f"  ✗ Failed to load config: {e}")
            return False

        errors = self.validate_config(config, name)
        if errors:
            print(f"  ✗ Configuration errors:")
            for error in errors:
                print(f"    - {error}")
            return False

        print(f"  ✓ Configuration valid")

        metadata = config['metadata']
        cwe_code = metadata['cwe_code']
        cwe_name = metadata['cwe_name']

        query = config['query']
        source = query.get('source', 'shared')

        analysis = config.get('analysis', {})
        # Support both new compression_level and old extract_min for backward compat
        if 'compression_level' in analysis:
            compression_level = analysis['compression_level']
        elif analysis.get('extract_min', False):
            compression_level = 2
        else:
            compression_level = 0
        cpu_threads = analysis.get('cpu_threads', 10)

        # Create output directory
        output_dir = os.path.join(self.builds_dir, f'CWE-{cwe_code}')
        os.makedirs(output_dir, exist_ok=True)

        if source != 'local':
            print(f"  ✗ Only 'local' query source is supported (got: {source})")
            return False

        return self._build_local(output_dir, config, cwe_code, cwe_name, compression_level, cpu_threads, force)

    def _build_local(self, output_dir: str, config: Dict[str, Any],
                     cwe_code: str, cwe_name: str, compression_level: int, cpu_threads: int, force: bool) -> bool:
        """Build a local query module."""
        query = config['query']

        # 1. Copy CodeQL library
        codeql_lib_source = self.get_codeql_lib_source(config)
        if not codeql_lib_source:
            print(f"  ✗ No valid CodeQL library source found")
            return False

        target_codeql_dir = os.path.join(output_dir, 'codeql')

        if os.path.exists(target_codeql_dir):
            if force:
                print(f"  - Removing existing codeql/ directory...")
                if os.path.islink(target_codeql_dir):
                    os.unlink(target_codeql_dir)
                else:
                    shutil.rmtree(target_codeql_dir)
            else:
                print(f"  ⚠ codeql/ already exists, skipping (use --force to overwrite)")

        if os.path.lexists(target_codeql_dir) and not os.path.exists(target_codeql_dir):
            os.unlink(target_codeql_dir)

        if not os.path.exists(target_codeql_dir) and query.get('library_mode') == 'symlink':
            os.symlink(os.path.relpath(codeql_lib_source, output_dir), target_codeql_dir)
            print(f"  ✓ Linked shared CodeQL library")

        if not os.path.exists(target_codeql_dir):
            lib_size = self._get_dir_size(codeql_lib_source)
            print(f"  - Copying CodeQL library ({lib_size:.1f} MB)...")

            result = os.system(f"cp -r '{codeql_lib_source}' '{target_codeql_dir}'")
            if result != 0:
                try:
                    shutil.copytree(codeql_lib_source, target_codeql_dir)
                except Exception as e:
                    print(f"  ✗ Failed to copy CodeQL library: {e}")
                    return False

            print(f"  ✓ Copied CodeQL library")

        # 2. Copy query file
        ql_source = query.get('ql_source_path')
        target_query_path = os.path.join(output_dir, 'query.ql')

        if os.path.exists(target_query_path) and not force:
            print(f"  ⚠ query.ql already exists, skipping")
        else:
            shutil.copy2(ql_source, target_query_path)
            print(f"  ✓ Copied query.ql")

        for module_path, dependency in query.get('ql_dependencies', {}).items():
            target = os.path.join(output_dir, module_path)
            os.makedirs(os.path.dirname(target), exist_ok=True)
            if force or not os.path.exists(target):
                shutil.copy2(dependency, target)

        # 3. Generate codeql.py
        codeql_py_path = os.path.join(output_dir, 'codeql.py')
        if os.path.exists(codeql_py_path) and not force:
            print(f"  ⚠ codeql.py already exists, skipping")
        else:
            content = CODEQL_LOCAL_TEMPLATE.format(
                cwe_code=cwe_code,
                cwe_name=cwe_name,
                compression_level=compression_level,
                cpu_threads=cpu_threads
            )
            with open(codeql_py_path, 'w') as f:
                f.write(content)
            print(f"  ✓ Generated codeql.py")

        # 4. Create __init__.py
        init_path = os.path.join(output_dir, '__init__.py')
        if not os.path.exists(init_path) or force:
            with open(init_path, 'w') as f:
                f.write(f"# CWE-{cwe_code}: {cwe_name}\n")
            print(f"  ✓ Created __init__.py")

        # 5. Create qlpack.yml
        qlpack_path = os.path.join(output_dir, 'qlpack.yml')
        if not os.path.exists(qlpack_path) or force:
            qlpack_name = cwe_code.lower().replace("-", "")
            with open(qlpack_path, 'w') as f:
                f.write(f"""name: {qlpack_name}
version: 0.0.0
dependencies:
  codeql/cpp-all: "*"
""")
            print(f"  ✓ Created qlpack.yml")

        print(f"  ✓ Build complete: {output_dir}")
        return True

    def _get_dir_size(self, path: str) -> float:
        """Get directory size in MB."""
        total_size = 0
        for dirpath, dirnames, filenames in os.walk(path):
            for filename in filenames:
                filepath = os.path.join(dirpath, filename)
                if os.path.exists(filepath):
                    total_size += os.path.getsize(filepath)
        return total_size / (1024 * 1024)

    def build_all(self, force: bool = False) -> Dict[str, bool]:
        """Build all scanner modules."""
        results = {}
        configs = self.list_configs()

        print(f"Found {len(configs)} scanner configs to build")

        for name in configs:
            try:
                results[name] = self.build(name, force)
            except Exception as e:
                print(f"  ✗ Error building {name}: {e}")
                results[name] = False

        # Print summary
        print(f"\n{'='*50}")
        print("Build Summary:")
        succeeded = sum(1 for v in results.values() if v)
        failed = sum(1 for v in results.values() if not v)
        print(f"  Succeeded: {succeeded}")
        print(f"  Failed: {failed}")

        return results

    def verify(self, name: str, test_db: str = None) -> Tuple[bool, List[str]]:
        """
        Verify a built module is complete and optionally run a test.

        Args:
            name: Config name
            test_db: Optional CodeQL database path to run a test

        Returns:
            Tuple of (success, list of issues)
        """
        issues = []

        # Load config to get cwe_code
        try:
            config = self.load_config(name)
        except Exception as e:
            return False, [f"Failed to load config: {e}"]

        cwe_code = config['metadata']['cwe_code']
        output_dir = os.path.join(self.builds_dir, f'CWE-{cwe_code}')

        if not os.path.exists(output_dir):
            return False, [f"Build directory not found: {output_dir}"]

        # Check required files
        required_files = ['codeql.py', '__init__.py']
        for filename in required_files:
            filepath = os.path.join(output_dir, filename)
            if not os.path.exists(filepath):
                issues.append(f"Missing required file: {filename}")

        query = config.get('query', {})

        # For local queries, check codeql/ and query.ql
        if query.get('source') == 'local':
            codeql_dir = os.path.join(output_dir, 'codeql')
            if not os.path.exists(codeql_dir):
                issues.append("Missing codeql/ directory for local query")

            query_ql = os.path.join(output_dir, 'query.ql')
            if not os.path.exists(query_ql):
                issues.append("Missing query.ql for local query")

            qlpack = os.path.join(output_dir, 'qlpack.yml')
            if not os.path.exists(qlpack):
                issues.append("Missing qlpack.yml for local query")
            for module_path in query.get('ql_dependencies', {}):
                if not os.path.isfile(os.path.join(output_dir, module_path)):
                    issues.append(f"Missing QL dependency: {module_path}")

        if issues:
            return False, issues

        # Run test if test_db provided
        if test_db:
            print(f"\nRunning test with database: {test_db}")
            test_result, test_issues = self._run_test(output_dir, cwe_code, test_db)
            if not test_result:
                issues.extend(test_issues)
                return False, issues

        return True, []

    def _run_test(self, output_dir: str, cwe_code: str, test_db: str) -> Tuple[bool, List[str]]:
        """Run a test on the built module."""
        issues = []

        # Create a test script
        test_script = f'''
import sys
import os
import tempfile

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname("{output_dir}")))

# Import the module
from builds.CWE_{cwe_code.replace("-", "_")}.codeql import CodeQLAnalysisHelper

# Create helper
with tempfile.NamedTemporaryFile(suffix='.db', delete=False) as f:
    db_path = f.name

try:
    helper = CodeQLAnalysisHelper(db_path=db_path, codeql_db_path="{test_db}")
    print("✓ Module imported and initialized successfully")
except Exception as e:
    print(f"✗ Failed to initialize: {{e}}")
    sys.exit(1)
finally:
    if os.path.exists(db_path):
        os.remove(db_path)
'''

        try:
            result = subprocess.run(
                ['python3', '-c', test_script],
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode != 0:
                issues.append(f"Test failed: {result.stderr}")
                return False, issues

            print(result.stdout)
            return True, []

        except subprocess.TimeoutExpired:
            issues.append("Test timed out")
            return False, issues
        except Exception as e:
            issues.append(f"Test error: {e}")
            return False, issues


def main():
    """Command-line interface."""
    import argparse

    parser = argparse.ArgumentParser(
        description='Build CWE scanner modules from YAML configuration'
    )
    parser.add_argument(
        'action',
        choices=['build', 'build-all', 'verify', 'list'],
        help='Action to perform'
    )
    parser.add_argument(
        'name',
        nargs='?',
        help='Config name (e.g., 416-UseAfterFree)'
    )
    parser.add_argument(
        '--force', '-f',
        action='store_true',
        help='Force rebuild even if files exist'
    )
    parser.add_argument(
        '--test-db',
        help='CodeQL database path for verification test'
    )
    parser.add_argument(
        '--config-dir',
        help='Directory containing user-supplied scanner YAML configurations'
    )

    args = parser.parse_args()

    builder = ScannerBuilder(configs_dir=args.config_dir)

    if args.action == 'list':
        configs = builder.list_configs()
        print(f"Found {len(configs)} scanner configs:")
        for config in configs:
            print(f"  - {config}")

    elif args.action == 'build':
        if not args.name:
            print("Error: 'build' requires a config name")
            sys.exit(1)
        success = builder.build(args.name, args.force)
        sys.exit(0 if success else 1)

    elif args.action == 'build-all':
        results = builder.build_all(args.force)
        failed = sum(1 for v in results.values() if not v)
        sys.exit(0 if failed == 0 else 1)

    elif args.action == 'verify':
        if not args.name:
            print("Error: 'verify' requires a config name")
            sys.exit(1)
        success, issues = builder.verify(args.name, args.test_db)
        if success:
            print(f"✓ {args.name} verified successfully")
        else:
            print(f"✗ {args.name} has issues:")
            for issue in issues:
                print(f"  - {issue}")
        sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
